### ISSUE TITLE
Unit tests won't run

### ISSUE THREAD

**Issue by timhunt** [moodlehq/rtlcss-php#3]
I just cloned this repo, to do a bug fix.

After running `php composer.phar install`, `vendor/bin/phpunit` started working, but then it hit the error

Fatal error: Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in C:\Users\tjh238\workspace\rtlcss-php\vendor\sebastian\comparator\src\DOMNodeComparator.php on line 48

Which is a pain. Means I cannot add tests to my new fix (but, the fix works to fix processing of the OU Moodle theme, and makes logical sense, so I think it is good.)

**Comment by sarjona** [comment]
Hi @timhunt !
Thanks for raising this issue! I haven't been able to reproduce this error locally... PHPUnit tests are passing always (at least in my local instance). I've tried with different PHP versions (7.3 and 7.4) in my local instance (Ubuntu 20.04):

![phpunit_rtlcsstest](https://user-images.githubusercontent.com/900389/150511716-30d60d73-a230-48c6-ba62-3cb71a3ebb0e.png)

Could you please add more information to help us to reproduce the error? TIA!

**Comment by timhunt** [comment]
Thanks for looking.

Obvisously, I am stuck on Windows here, but this should not matter for this pure PHP stuff which just does string manipulation.

I was being lazy and just using composer from Moodle, which was generating warnings:

```
$ php ../moodle/composer.phar install
You are using Composer 1 which is deprecated. You should upgrade to Composer 2,
see https://blog.packagist.com/deprecating-composer-1-support/
```

However, that was not the issue. I did it properly, installed Latest Composer. Removed the vendor directory, re-installed, and I still get the same fatal error.

```
$ php -v
PHP 7.4.23 (cli) (built: Aug 25 2021 09:37:03) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.23, Copyright (c), by Zend Technologies
```

I am doing all this in a GitBash terminal on Windows.

The other thing I was diong was just running 

```
vendor/bin/phpunit
```

but I tried 

```
vendor/bin/phpunit tests/MoodleHQ/RTLCSS/RTLCSSTest.php
```

and I still get the same errors.

**Comment by timhunt** [comment]
The error seems perfectly valid. If I make this minimal testcase in a separate PHP file:

```
<?php

declare(strict_types = 1);

class ObjectComparator {
    public function assertEquals($expected, $actual, $delta = 0.0, $canonicalize = false, $ignoreCase = false, array &$processed = array()) {
    }
}

class DOMNodeComparator extends ObjectComparator {
    public function assertEquals($expected, $actual, $delta = 0.0, $canonicalize = false, $ignoreCase = false) {
    }
}

$test = new DOMNodeComparator();
$test->assertEquals('test', 'test');
echo "OK";
```

and run that, then I get a Warning, not a Fatal error.

Acutally, I just noticed that this is currently using PHPUnit 5.5. I guess before we bang our heads on this too much, we should start by upgrading that!

Thanks again for looking :-)

**Comment by sarjona** [comment]
Hi @timhunt !
Thanks for the information :-) 

I can still not reproduce the error you're facing. I'm using composer 2.2.4. Do you know what's the version of the sebastian/comparator that you're using? I've been working to release a new composer.json file (to upgrade some values, like the PHP version you suggested), and it's working when I install composer and also when I update it (in that case it uses 4.0.6). I'm sharing with you my WIP branch and it would be great if you could confirm us if it fixes the PHPUnit errors you're facing: https://github.com/moodlehq/rtlcss-php/compare/master...sarjona:upgradephpversion

I'll send a pull request next week with these and other changes (like support to GHA).

**Comment by timhunt** [comment]
I think that you should not spend time on my problem.

If you could get github actions working, then that would help everyone, and would generally be awesome, so I think you should direct your energies there. :-)

**Comment by scara** [comment]
Hi @timhunt,
I'm on Windows and will try later.

I found https://github.com/sebastianbergmann/comparator/issues/51#issuecomment-452132726 and https://github.com/sebastianbergmann/comparator/issues/51#issuecomment-526561786 which could be helpful:
> In case anyone else stumbles on this issue, upgrading sebastian/comparator to v1.2.4 worked for me
> ```
> $ composer update sebastian/comparator
> (...)
>   - Updating sebastian/comparator (1.2.0 => 1.2.4): Loading from cache
> (...)
> ```

HTH,
Matteo

**Comment by sarjona** [comment]
I've just sent the pull request to add GitHub Actions support (and bump the PHP version): https://github.com/moodlehq/rtlcss-php/pull/6

Once it will be integrated, it will be easier for everybody to run these PHPUnit tests ;-)

Thanks Matteo for pointing to this issue that might help Tim to fix the errors he is facing with his local instance!
